server:
  port: 8083
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/qiniu?serverTimezone=UTC&userUnicode=true&useSSL=false&
    password: 2002.06.25abcj
    username: root
    driver-class-name: com.mysql.cj.jdbc.Driver