# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: qiniu 

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        architecture: x64
        cache: maven
    # 测试
    - name: Run the Maven verify phase
      run: cd qiniu-server && mvn --batch-mode --update-snapshots verify
      
    # 打包
    - name: Build with Maven
      run: cd qiniu-server && mvn -B package --file pom.xml
    
    # 移动security包
    - name: move package security
      run: mkdir staging && cd qiniu-server/qiniu-security/ && cp target/*.jar staging
    # 移动video包  
    - name: move package video
      run: cd qiniu-server/qiniu-video/ && cp target/*.jar staging
    - name: show path
      run: pwd && ls && cd qiniu-server && pwd && ls
    - uses: actions/upload-artifact@v3
      with:
        name: Package
        path: staging

    # 利用action把build好的文件上传到服务器/www/qiniu路径下,需要确认此目录已在服务端创建
    - name: deploy file to server
      uses: zhenyuWang/Upload-File-Action@v1.0.1
      with:  
        username: 'root'   #ssh user name
        server: '${{ secrets.SERVER_IP }}' #引用之前创建好的secret
        port: 22
        ssh_private_key: ${{ secrets.test }} #引用之前创建好的secret
        local_path: './staging/*'  # 对应我们项目build的文件夹路径
        remote_path: '/www/qiniu'
  # Optional: Uploads the full dependency graph to GitHub to improve the quality of Dependabot alerts this repository can receive
    # - name: Update dependency graph
    #   uses: advanced-security/maven-dependency-submission-action@571e99aab1055c2e71a1e2309b9691de18d6b7d6
