# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: web-publish

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x, 16.x, 18.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - run: ls && cd web/Qiniuuu
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm ci
    - run: npm run build --if-present
    - run: npm test
    
    - name: deploy file to server
      uses: zhenyuWang/Upload-File-Action@v1.0.1
      with:  
        username: 'root'   #ssh user name
        server: '${{ secrets.SERVER_IP }}' #引用之前创建好的secret
        port: 22
        ssh_private_key: ${{ secrets.test }} #引用之前创建好的secret
        local_path: "./dist/*"  # 对应我们项目build的文件夹路径
        target_path: '/www/qiniu/web'
